name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag twistedpolitiks/gluetun-qbittorrent-port-manager:${{ github.sha }}
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: Docker Push
      run: docker push twistedpolitiks/gluetun-qbittorrent-port-manager:${{ github.sha }}
